---
title: "Credit Logistic Regression"
author: "Lei Deng, ti7597, STAT6620"
date: "May 18, 2017"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Step 1 - Colleting data

Read the data to the R

```{r}
# load the necessary library
library(Amelia)
library(ROCR)

credit <- read.csv("credit.csv")
```

## Step 2 - Exploring and preparing the data

```{r}
# examine the credit data
str(credit)

# logisitic regression

# set up trainning and test data sets

indx = sample(1:nrow(credit), as.integer(0.9*nrow(credit)))
indx

credit_train = credit[indx,]
credit_test = credit[-indx,]

credit_train_labels = credit[indx,17]
credit_test_labels = credit[-indx,17]   

# Check if there are any missing values

missmap(credit, main = "Missing values vs observed")

# number of missing values in each column

sapply(credit,function(x) sum(is.na(x)))

# number of unique values in each column

sapply(credit, function(x) length(unique(x)))
```

## Step3 - Training a model on the data

```{r}
# fit the logistic regression model, with all predictor variables

model <- glm(default ~.,family=binomial(link='logit'),data=credit_train)
model

summary(model)

anova(model, test="Chisq")

# drop the insignificant predictors, alpha = 0.10

model <- glm(default ~ checking_balance + months_loan_duration + credit_history +  percent_of_income + age,family=binomial(link='logit'),data=credit_train)
model

summary(model)

anova(model, test="Chisq")
```

## step4 - Evaluating model performance

```{r}
# check Accuracy

fitted.results <- predict(model,newdata=credit_test,type='response')
fitted.results <- ifelse(fitted.results > 0.5,1,0)

misClasificError <- mean(fitted.results != credit_test$default)
print(paste('Accuracy',1-misClasificError))
```

## step5 - Improving model performance

```{r}
# Because this data set is so small, it is possible that the test data set
# does not contain both 0 and 1 values.  If this happens the code will not
# run.  And since the test data set is so small the ROC is not useful here
# but the code is provided.

p <- predict(model, newdata=credit_test, type="response")
pr <- prediction(p, credit_test$default)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)

auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
auc
```

