---
title: "OCR letter analysis"
author: "Lei Deng, STAT 6620, ti7597"
date: "May 25, 2017"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Step 1 - Colleting data

Read the data to the R

```{r}
# load the necessary library
library(kernlab)
library(h2o)

letters <- read.csv("letterdata.csv")

```

## Step 2 - Exploring and preparing the data

```{r}
str(letters)

# divide into training and test data
letters_train <- letters[1:16000, ]
letters_test  <- letters[16001:20000, ]
```

## Step3 - Training a model on the data

```{r}
# begin by training a simple linear SVM

letter_classifier <- ksvm(letter ~ ., data = letters_train,
                          kernel = "vanilladot")

# look at basic information about the model
letter_classifier
```


## step4 - Evaluating model performance

```{r}
# predictions on testing dataset
letter_predictions <- predict(letter_classifier, letters_test)

head(letter_predictions)

table(letters_test$letter, letter_predictions)

# look only at agreement vs. non-agreement
# construct a vector of TRUE/FALSE indicating correct/incorrect predictions
agreement <- letter_predictions == letters_test$letter
table(agreement)
prop.table(table(agreement))
```

## step5 - Improving model performance

```{r}
set.seed(12345)
letter_classifier_rbf <- ksvm(letter ~ ., data = letters_train, kernel = "rbfdot")
letter_predictions_rbf <- predict(letter_classifier_rbf, letters_test)

table(letters_test$letter, letter_predictions_rbf)

agreement_rbf <- letter_predictions_rbf == letters_test$letter
table(agreement_rbf)
prop.table(table(agreement_rbf))

# using h2o deeplearning



h2o.init()

letterdata.hex <- h2o.importFile("letterdata.csv")

summary(letterdata.hex)

splits <- h2o.splitFrame(letterdata.hex, 0.80, seed=1234)

dl <- h2o.deeplearning(x=2:17,y="letter",training_frame=splits[[1]],activation = "RectifierWithDropout", 
                       hidden = c(16,16,16), distribution = "multinomial",input_dropout_ratio=0.2,
                       epochs = 10,nfold=5,variable_importances = TRUE)

dl.predict <- h2o.predict (dl, splits[[2]])

dl@parameters

h2o.performance(dl)

h2o.varimp(dl)

h2o.shutdown()
```


